import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';
import { GeistSans } from 'geist/font/sans';
import type { Metadata } from 'next';
import './globals.css';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="es" className={GeistSans.className}>
			<body>
				<AppRouterCacheProvider options={{ enableCssLayer: false }}>{children}</AppRouterCacheProvider>
			</body>
		</html>
	);
}
